NProcess: icedcode::NProcess Class Reference
icedcode::NProcess Class Reference
Classes
class Object
Public Member Functions
void Flush ()
void SetDebug (bool)
void SetNbUsedProc (int nb_=-1)
int GetNbProc ()
int GetNbRunning ()
std::mutex * PrepareMutex (const std::string &)
void Lock (const std::string &key_)
void Unlock (const std::string &key_)
void ProcessAll (unsigned int step_=0)
void ForStep (bool &next_, std::list< unsigned int > step_list_)
void ForStep (bool &next_, unsigned int start_, unsigned int stop_)
void WaitRunning ()
void WaitThis (Object *)
void KillThis (Object *)
const std::list< Object * > & GetObjects () const
size_t GetNbObject () const
void AssynchRunThis (Object *obj_)
Public Member Functions inherited from icedcode::NSingle< NProcess >
void SetDebug (bool debug_)
Static Public Member Functions
static void ProcessThis (Object *obj_)
static void RunThis (Object *obj_)
Static Public Member Functions inherited from icedcode::NSingle< NProcess >
static NProcess * GetIt ()
static void kill ()
Private Member Functions
void ProcessGarbageCollector ()
void Init ()
void Add (Object *)
Private Attributes
std::atomic< int > __count
bool __debug
bool __init
std::atomic< int > __nb_thread
std::atomic< int > __nb_running
std::mutex __nb_thread_counter_mtx
std::mutex __locker_mtx
std::map< std::string, std::mutex * > __mutex_lst
std::list< Object * > __obj_lst
std::map< Object *, std::thread * > __run_thread
std::list< std::thread * > __threads
Friends
class NSingle< NProcess >
Additional Inherited Members
Protected Attributes inherited from icedcode::NSingle< NProcess >
bool __debug
Static Protected Attributes inherited from icedcode::NSingle< NProcess >
static NProcess * __sgt
Member Function Documentation
AssynchRunThis()
void icedcode::NProcess::AssynchRunThis (Object * obj_)
launch a thread for an object.
Parameters
obj_ to be run.
Referenced by GetNbRunning().
Flush()
void icedcode::NProcess::Flush () virtual
Remove all user objects from the running list without deleting them.
Implements icedcode::NSingle< NProcess >.
Referenced by icedcode::NProcess::Object::Unlock().
GetNbRunning()
int icedcode::NProcess::GetNbRunning () inline
Returns
the threads currently running the Run methods
References AssynchRunThis(), KillThis(), icedcode::NProcess::Object::Lock(), PrepareMutex(), ProcessAll(), ProcessThis(), icedcode::NProcess::Object::Unlock(), WaitRunning(), and WaitThis().
KillThis()
void icedcode::NProcess::KillThis (Object *)
Stop the running object, without deleting it.
Referenced by GetNbRunning().
Lock()
void icedcode::NProcess::Lock (const std::string & key_)
Easy to use internal mutex method to be used in Run and Process for multi-theading safety. Slower than direct mutex usage, it uses a dictionary to classify the mutexes by user names. This method lock the mutex pointed by key_.
Parameters
key_ string naming the mutex.
PrepareMutex()
std::mutex* icedcode::NProcess::PrepareMutex (const std::string &)
Prepare the mutex with the given name.
Returns
mutex directly usable by the user.
Referenced by GetNbRunning().
ProcessAll()
void icedcode::NProcess::ProcessAll (unsigned int step_ = 0)
Launch all the object Process method in parallel (with a maximum of simultaneous number of used process). It can run only the object with given step number, which is a kind of user id. It waits the end of all the processes
Parameters
step_ id number to differentiate the object to processes
Referenced by GetNbRunning().
ProcessThis()
static void icedcode::NProcess::ProcessThis (Object * obj_) static
Process only one object.
Parameters
obj_
Referenced by GetNbRunning().
Unlock()
void icedcode::NProcess::Unlock (const std::string & key_)
Easy to use internal mutex method to be used in Run and Process for multi-theading safety. Slower than direct mutex usage, it uses a dictionary to classify the mutexes by user names. This method unlock the mutex pointed by key_, or just create the mutex if it does not exist.
Parameters
key_ string naming the mutex.
WaitRunning()
void icedcode::NProcess::WaitRunning ()
Wait for all the running objects
Referenced by GetNbRunning().
WaitThis()
void icedcode::NProcess::WaitThis (Object *)
Wait only for the given object running to finish.
Referenced by GetNbRunning().
The documentation for this class was generated from the following file:
include/NProcess/NProcess.h