Amoeba: icedcode::NProcess::Object Class Reference
icedcode::NProcess::Object Class Reference abstract
#include <NProcess.h>
Public Member Functions
Object (const Object &)
Object & operator= (const Object &)
unsigned int GetProcessId ()
unsigned int GetStep ()
virtual void PreProcess ()
virtual void Process ()=0
virtual void PostProcess ()
virtual void Run ()=0
void Lock (const std::string &key_)
void Unlock (const std::string &key_)
Private Attributes
size_t __current_process_id
std::atomic< size_t > __step__
Static Private Attributes
static std::atomic< size_t > __processes_id__
Detailed Description
Object to be used by inheritence for the multithread processes.
Member Function Documentation
Lock()
void icedcode::NProcess::Object::Lock (const std::string & key_) inline
Easy to use internal mutex method to be used in Run and Process for multi-theading safety. Slower than direct mutex usage, it uses a dictionary to classify the mutexes by user names. It's the dictionary from the singleton NProcess. This method lock the mutex pointed by key_.
Parameters
key_ string naming the mutex.
Referenced by icedcode::NProcess::GetNbRunning().
Process()
virtual void icedcode::NProcess::Object::Process () pure virtual
Process method correspond to the method that will be executed in parrallel The user have to implement it, even with something void if needed. It can be executed more than once, the user have to use his own mutexes to wait for it.
Run()
virtual void icedcode::NProcess::Object::Run () pure virtual
Run method correspond to the method that will be executed in parrallel The user have to implement it, even with something void if needed. It can be executed only once and the user can use the WaitForIt method to wait it.
Unlock()
void icedcode::NProcess::Object::Unlock (const std::string & key_) inline
Easy to use internal mutex method to be used in Run and Process for multi-theading safety. Slower than direct mutex usage, it uses a dictionary to classify the mutexes by user names. It's the dictionary from the singleton NProcess. This method unlock the mutex pointed by key_, or just create the mutex if it does not exist.
Parameters
key_ string naming the mutex.
References icedcode::NProcess::Flush().
Referenced by icedcode::NProcess::GetNbRunning().
The documentation for this class was generated from the following file:
include/NProcess/NProcess.h