Amoeba: my_std::map< _Key, _Tp, _Compare, _Alloc > Class Template Reference
my_std::map< _Key, _Tp, _Compare, _Alloc > Class Template Reference
Public Types
typedef _Key key_type
typedef _Tp mapped_type
typedef std::pair< const _Key, _Tp > value_type
typedef _Compare key_compare
typedef _Alloc allocator_type
typedef _Pair_alloc_type::pointer pointer
typedef _Pair_alloc_type::const_pointer const_pointer
typedef _Pair_alloc_type::reference reference
typedef _Pair_alloc_type::const_reference const_reference
typedef _Rep_type::iterator iterator
typedef _Rep_type::const_iterator const_iterator
typedef _Rep_type::size_type size_type
typedef _Rep_type::difference_type difference_type
typedef _Rep_type::reverse_iterator reverse_iterator
typedef _Rep_type::const_reverse_iterator const_reverse_iterator
Public Member Functions
map ()
Default constructor creates no elements.
map (const _Compare &__comp, const allocator_type &__a=allocator_type())
Creates a map with no elements.
map (const map &__x)
Map copy constructor.
template<typename _InputIterator >
map (_InputIterator __first, _InputIterator __last)
Builds a map from a range.
template<typename _InputIterator >
map (_InputIterator __first, _InputIterator __last, const _Compare &__comp, const allocator_type &__a=allocator_type())
Builds a map from a range.
map & operator= (const map &__x)
Map assignment operator.
allocator_type get_allocator () const
Get a copy of the memory allocation object.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
bool empty () const
size_type size () const
size_type max_size () const
mapped_type & operator[] (const key_type &__k)
Subscript ([]) access to map data.
mapped_type & at (const key_type &__k)
Access to map data.
const mapped_type & at (const key_type &__k) const
std::pair< iterator, bool > insert (const value_type &__x)
Attempts to insert a std::pair into the map.
iterator insert (iterator __position, const value_type &__x)
Attempts to insert a std::pair into the map.
template<typename _InputIterator >
void insert (_InputIterator __first, _InputIterator __last)
Template function that attempts to insert a range of elements.
void erase (iterator __position)
Erases an element from a map.
size_type erase (const key_type &__x)
Erases elements according to the provided key.
void erase (iterator __first, iterator __last)
Erases a [first,last) range of elements from a map.
void swap (map &__x)
Swaps data with another map.
void clear ()
key_compare key_comp () const
value_compare value_comp () const
iterator find (const key_type &__x)
Tries to locate an element in a map.
const_iterator find (const key_type &__x) const
Tries to locate an element in a map.
size_type count (const key_type &__x) const
Finds the number of elements with given key.
iterator lower_bound (const key_type &__x)
Finds the beginning of a subsequence matching given key.
const_iterator lower_bound (const key_type &__x) const
Finds the beginning of a subsequence matching given key.
iterator upper_bound (const key_type &__x)
Finds the end of a subsequence matching given key.
const_iterator upper_bound (const key_type &__x) const
Finds the end of a subsequence matching given key.
std::pair< iterator, iterator > equal_range (const key_type &__x)
Finds a subsequence matching given key.
std::pair< const_iterator, const_iterator > equal_range (const key_type &__x) const
Finds a subsequence matching given key.
Private Types
typedef _Alloc::value_type _Alloc_value_type
typedef _Alloc::template rebind< value_type >::other _Pair_alloc_type
This turns a red-black tree into a [multi]map.
typedef std::_Rb_tree< key_type, value_type, std::_Select1st< value_type >, key_compare, _Pair_alloc_type > _Rep_type
Private Member Functions
__glibcxx_class_requires (_Tp, _SGIAssignableConcept) __glibcxx_class_requires4(_Compare
_BinaryFunctionConcept __glibcxx_class_requires2 (value_type, _Alloc_value_type, _SameTypeConcept) public
Private Attributes
bool
_Key
_Rep_type _M_t
The actual tree structure.
Friends
template<typename _K1 , typename _T1 , typename _C1 , typename _A1 >
bool operator== (const map< _K1, _T1, _C1, _A1 > &, const map< _K1, _T1, _C1, _A1 > &)
template<typename _K1 , typename _T1 , typename _C1 , typename _A1 >
bool operator< (const map< _K1, _T1, _C1, _A1 > &, const map< _K1, _T1, _C1, _A1 > &)
Constructor & Destructor Documentation
map() [1/4]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> my_std::map< _Key, _Tp, _Compare, _Alloc >::map (const _Compare & __comp, const allocator_type & __a = allocator_type()) inline explicit
Creates a map with no elements.
Parameters
comp A comparison object.
a An allocator object.
map() [2/4]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> my_std::map< _Key, _Tp, _Compare, _Alloc >::map (const map< _Key, _Tp, _Compare, _Alloc > & __x) inline
Map copy constructor.
Parameters
x A map of identical element and allocator types.
The newly-created map uses a copy of the allocation object used by x.
References my_std::map< _Key, _Tp, _Compare, _Alloc >::_M_t, and my_std::map< _Key, _Tp, _Compare, _Alloc >::map().
map() [3/4]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> template<typename _InputIterator > my_std::map< _Key, _Tp, _Compare, _Alloc >::map (_InputIterator __first, _InputIterator __last) inline
Builds a map from a range.
Parameters
first An input iterator.
last An input iterator.
Create a map consisting of copies of the elements from [first,last). This is linear in N if the range is already sorted, and NlogN otherwise (where N is distance(first,last)).
map() [4/4]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> template<typename _InputIterator > my_std::map< _Key, _Tp, _Compare, _Alloc >::map (_InputIterator __first, _InputIterator __last, const _Compare & __comp, const allocator_type & __a = allocator_type()) inline
Builds a map from a range.
Parameters
first An input iterator.
last An input iterator.
comp A comparison functor.
a An allocator object.
Create a map consisting of copies of the elements from [first,last). This is linear in N if the range is already sorted, and NlogN otherwise (where N is distance(first,last)).
Member Function Documentation
at()
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> mapped_type& my_std::map< _Key, _Tp, _Compare, _Alloc >::at (const key_type & __k) inline
Access to map data.
Parameters
k The key for which data should be retrieved.
Returns
A reference to the data whose key is equivalent to k, if such a data is present in the map.
Exceptions
std::out_of_range If no such data is present.
References my_std::map< _Key, _Tp, _Compare, _Alloc >::end(), my_std::map< _Key, _Tp, _Compare, _Alloc >::key_comp(), and my_std::map< _Key, _Tp, _Compare, _Alloc >::lower_bound().
begin() [1/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> iterator my_std::map< _Key, _Tp, _Compare, _Alloc >::begin () inline
Returns a read/write iterator that points to the first pair in the map. Iteration is done in ascending order according to the keys.
begin() [2/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_iterator my_std::map< _Key, _Tp, _Compare, _Alloc >::begin () const inline
Returns a read-only (constant) iterator that points to the first pair in the map. Iteration is done in ascending order according to the keys.
clear()
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> void my_std::map< _Key, _Tp, _Compare, _Alloc >::clear () inline
Erases all elements in a map. Note that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Referenced by my_std::map< _Key, _Tp, _Compare, _Alloc >::operator=().
count()
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> size_type my_std::map< _Key, _Tp, _Compare, _Alloc >::count (const key_type & __x) const inline
Finds the number of elements with given key.
Parameters
x Key of (key, value) pairs to be located.
Returns
Number of elements with specified key.
This function only makes sense for multimaps; for map the result will either be 0 (not present) or 1 (present).
empty()
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> bool my_std::map< _Key, _Tp, _Compare, _Alloc >::empty () const inline
Returns true if the map is empty. (Thus begin() would equal end().)
end() [1/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> iterator my_std::map< _Key, _Tp, _Compare, _Alloc >::end () inline
Returns a read/write iterator that points one past the last pair in the map. Iteration is done in ascending order according to the keys.
Referenced by my_std::map< _Key, _Tp, _Compare, _Alloc >::at(), and my_std::map< _Key, _Tp, _Compare, _Alloc >::operator[]().
end() [2/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_iterator my_std::map< _Key, _Tp, _Compare, _Alloc >::end () const inline
Returns a read-only (constant) iterator that points one past the last pair in the map. Iteration is done in ascending order according to the keys.
equal_range() [1/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> std::pair<iterator, iterator> my_std::map< _Key, _Tp, _Compare, _Alloc >::equal_range (const key_type & __x) inline
Finds a subsequence matching given key.
Parameters
x Key of (key, value) pairs to be located.
Returns
Pair of iterators that possibly points to the subsequence matching given key.
This function is equivalent to
std::make_pair(c.lower_bound(val),
               c.upper_bound(val))
(but is faster than making the calls separately).
This function probably only makes sense for multimaps.
equal_range() [2/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> std::pair<const_iterator, const_iterator> my_std::map< _Key, _Tp, _Compare, _Alloc >::equal_range (const key_type & __x) const inline
Finds a subsequence matching given key.
Parameters
x Key of (key, value) pairs to be located.
Returns
Pair of read-only (constant) iterators that possibly points to the subsequence matching given key.
This function is equivalent to
std::make_pair(c.lower_bound(val),
               c.upper_bound(val))
(but is faster than making the calls separately).
This function probably only makes sense for multimaps.
References my_std::map< _Key, _Tp, _Compare, _Alloc >::_M_t, and my_std::map< _Key, _Tp, _Compare, _Alloc >::swap().
erase() [1/3]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> void my_std::map< _Key, _Tp, _Compare, _Alloc >::erase (iterator __position) inline
Erases an element from a map.
Parameters
position An iterator pointing to the element to be erased.
This function erases an element, pointed to by the given iterator, from a map. Note that this function only erases the element, and that if the element is itself a pointer, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
erase() [2/3]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> size_type my_std::map< _Key, _Tp, _Compare, _Alloc >::erase (const key_type & __x) inline
Erases elements according to the provided key.
Parameters
x Key of element to be erased.
Returns
The number of elements erased.
This function erases all the elements located by the given key from a map. Note that this function only erases the element, and that if the element is itself a pointer, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
erase() [3/3]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> void my_std::map< _Key, _Tp, _Compare, _Alloc >::erase (iterator __first, iterator __last) inline
Erases a [first,last) range of elements from a map.
Parameters
first Iterator pointing to the start of the range to be erased.
last Iterator pointing to the end of the range to be erased.
This function erases a sequence of elements from a map. Note that this function only erases the element, and that if the element is itself a pointer, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
References my_std::map< _Key, _Tp, _Compare, _Alloc >::swap().
find() [1/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> iterator my_std::map< _Key, _Tp, _Compare, _Alloc >::find (const key_type & __x) inline
Tries to locate an element in a map.
Parameters
x Key of (key, value) pair to be located.
Returns
Iterator pointing to sought-after element, or end() if not found.
This function takes a key and tries to locate the element with which the key matches. If successful the function returns an iterator pointing to the sought after pair. If unsuccessful it returns the past-the-end (end()) iterator.
find() [2/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_iterator my_std::map< _Key, _Tp, _Compare, _Alloc >::find (const key_type & __x) const inline
Tries to locate an element in a map.
Parameters
x Key of (key, value) pair to be located.
Returns
Read-only (constant) iterator pointing to sought-after element, or end() if not found.
This function takes a key and tries to locate the element with which the key matches. If successful the function returns a constant iterator pointing to the sought after pair. If unsuccessful it returns the past-the-end (end()) iterator.
insert() [1/3]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> std::pair<iterator, bool> my_std::map< _Key, _Tp, _Compare, _Alloc >::insert (const value_type & __x) inline
Attempts to insert a std::pair into the map.
Parameters
x Pair to be inserted (see std::make_pair for easy creation of pairs).
Returns
A pair, of which the first element is an iterator that points to the possibly inserted pair, and the second is a bool that is true if the pair was actually inserted.
This function attempts to insert a (key, value) pair into the map. A map relies on unique keys and thus a pair is only inserted if its first element (the key) is not already present in the map.
Insertion requires logarithmic time.
Referenced by my_std::map< _Key, _Tp, _Compare, _Alloc >::operator=(), and my_std::map< _Key, _Tp, _Compare, _Alloc >::operator[]().
insert() [2/3]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> iterator my_std::map< _Key, _Tp, _Compare, _Alloc >::insert (iterator __position, const value_type & __x) inline
Attempts to insert a std::pair into the map.
Parameters
position An iterator that serves as a hint as to where the pair should be inserted.
x Pair to be inserted (see std::make_pair for easy creation of pairs).
Returns
An iterator that points to the element with key of x (may or may not be the pair passed in).
This function is not concerned about whether the insertion took place, and thus does not return a boolean like the single-argument insert() does. Note that the first parameter is only a hint and can potentially improve the performance of the insertion process. A bad hint would cause no gains in efficiency.
See http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt07ch17.html for more on "hinting".
Insertion requires logarithmic time (if the hint is not taken).
insert() [3/3]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> template<typename _InputIterator > void my_std::map< _Key, _Tp, _Compare, _Alloc >::insert (_InputIterator __first, _InputIterator __last) inline
Template function that attempts to insert a range of elements.
Parameters
first Iterator pointing to the start of the range to be inserted.
last Iterator pointing to the end of the range.
Complexity similar to that of the range constructor.
key_comp()
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> key_compare my_std::map< _Key, _Tp, _Compare, _Alloc >::key_comp () const inline
Returns the key comparison object out of which the map was constructed.
Referenced by my_std::map< _Key, _Tp, _Compare, _Alloc >::at(), and my_std::map< _Key, _Tp, _Compare, _Alloc >::operator[]().
lower_bound() [1/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> iterator my_std::map< _Key, _Tp, _Compare, _Alloc >::lower_bound (const key_type & __x) inline
Finds the beginning of a subsequence matching given key.
Parameters
x Key of (key, value) pair to be located.
Returns
Iterator pointing to first element equal to or greater than key, or end().
This function returns the first element of a subsequence of elements that matches the given key. If unsuccessful it returns an iterator pointing to the first element that has a greater value than given key or end() if no such element exists.
Referenced by my_std::map< _Key, _Tp, _Compare, _Alloc >::at(), and my_std::map< _Key, _Tp, _Compare, _Alloc >::operator[]().
lower_bound() [2/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_iterator my_std::map< _Key, _Tp, _Compare, _Alloc >::lower_bound (const key_type & __x) const inline
Finds the beginning of a subsequence matching given key.
Parameters
x Key of (key, value) pair to be located.
Returns
Read-only (constant) iterator pointing to first element equal to or greater than key, or end().
This function returns the first element of a subsequence of elements that matches the given key. If unsuccessful it returns an iterator pointing to the first element that has a greater value than given key or end() if no such element exists.
max_size()
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> size_type my_std::map< _Key, _Tp, _Compare, _Alloc >::max_size () const inline
Returns the maximum size of the map.
operator=()
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> map& my_std::map< _Key, _Tp, _Compare, _Alloc >::operator= (const map< _Key, _Tp, _Compare, _Alloc > & __x) inline
Map assignment operator.
The dtor only erases the elements, and note that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Parameters
x A map of identical element and allocator types.
All the elements of x are copied, but unlike the copy constructor, the allocator object is not copied.
References my_std::map< _Key, _Tp, _Compare, _Alloc >::_M_t, my_std::map< _Key, _Tp, _Compare, _Alloc >::clear(), my_std::map< _Key, _Tp, _Compare, _Alloc >::insert(), and my_std::map< _Key, _Tp, _Compare, _Alloc >::swap().
operator[]()
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> mapped_type& my_std::map< _Key, _Tp, _Compare, _Alloc >::operator[] (const key_type & __k) inline
Subscript ([]) access to map data.
Parameters
k The key for which data should be retrieved.
Returns
A reference to the data of the (key,data) pair.
Allows for easy lookup with the subscript ([]) operator. Returns data associated with the key specified in subscript. If the key does not exist, a pair with that key is created using default values, which is then returned.
Lookup requires logarithmic time.
References my_std::map< _Key, _Tp, _Compare, _Alloc >::end(), my_std::map< _Key, _Tp, _Compare, _Alloc >::insert(), my_std::map< _Key, _Tp, _Compare, _Alloc >::key_comp(), and my_std::map< _Key, _Tp, _Compare, _Alloc >::lower_bound().
rbegin() [1/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> reverse_iterator my_std::map< _Key, _Tp, _Compare, _Alloc >::rbegin () inline
Returns a read/write reverse iterator that points to the last pair in the map. Iteration is done in descending order according to the keys.
rbegin() [2/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_reverse_iterator my_std::map< _Key, _Tp, _Compare, _Alloc >::rbegin () const inline
Returns a read-only (constant) reverse iterator that points to the last pair in the map. Iteration is done in descending order according to the keys.
rend() [1/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> reverse_iterator my_std::map< _Key, _Tp, _Compare, _Alloc >::rend () inline
Returns a read/write reverse iterator that points to one before the first pair in the map. Iteration is done in descending order according to the keys.
rend() [2/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_reverse_iterator my_std::map< _Key, _Tp, _Compare, _Alloc >::rend () const inline
Returns a read-only (constant) reverse iterator that points to one before the first pair in the map. Iteration is done in descending order according to the keys.
size()
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> size_type my_std::map< _Key, _Tp, _Compare, _Alloc >::size () const inline
Returns the size of the map.
swap()
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> void my_std::map< _Key, _Tp, _Compare, _Alloc >::swap (map< _Key, _Tp, _Compare, _Alloc > & __x) inline
Swaps data with another map.
Parameters
x A map of the same element and allocator types.
This exchanges the elements between two maps in constant time. (It is only swapping a pointer, an integer, and an instance of the Compare type (which itself is often stateless and empty), so it should be quite fast.) Note that the global std::swap() function is specialized such that std::swap(m1,m2) will feed to this function.
References my_std::map< _Key, _Tp, _Compare, _Alloc >::_M_t.
Referenced by my_std::map< _Key, _Tp, _Compare, _Alloc >::equal_range(), my_std::map< _Key, _Tp, _Compare, _Alloc >::erase(), and my_std::map< _Key, _Tp, _Compare, _Alloc >::operator=().
upper_bound() [1/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> iterator my_std::map< _Key, _Tp, _Compare, _Alloc >::upper_bound (const key_type & __x) inline
Finds the end of a subsequence matching given key.
Parameters
x Key of (key, value) pair to be located.
Returns
Iterator pointing to the first element greater than key, or end().
upper_bound() [2/2]
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> const_iterator my_std::map< _Key, _Tp, _Compare, _Alloc >::upper_bound (const key_type & __x) const inline
Finds the end of a subsequence matching given key.
Parameters
x Key of (key, value) pair to be located.
Returns
Read-only (constant) iterator pointing to first iterator greater than key, or end().
value_comp()
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >> value_compare my_std::map< _Key, _Tp, _Compare, _Alloc >::value_comp () const inline
Returns a value comparison object, built from the key comparison object out of which the map was constructed.
The documentation for this class was generated from the following file:
include/NProcess/thread_map.h